openapi: "3.0.0"

info:
  title: ESPN API - NBA
  version: 0.0.1
  contact:
    email: israel.souza@summit-bra.com

servers:
  - url: https://apimdemoapiops.azure-api.net/nba

paths:
  /teams:
    get:
      summary: GetTeams
      tags:
        - "Espn Nba"
      responses:
        '200':
          description: Retorna uma lista com todos os times da Liga
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/TeamSchema"

  
  /nba/teams/{team}:
    get:
      operationId: GetTeamByAbbreviation
      summary: GetTeamByAbbreviation
      tags:
        - "Espn Nba"
      parameters:
        - in: path
          name: team
          required: true
          schema:
            type: string
  
          example: 'bkn'

      responses:
        '200':
          description: Retorna um Time especifico da NBA
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamSchema"

        '404':
          description: Time não encontrado

        '400':
          description: Parametro Inválido
          

components:
  schemas:
    TeamSchema:
      properties:
        id:
          type: string
          description: Id

        abbreviation:
          type: string
          description: Abreviação do nome da Franquia
          example: BKN

        location:
          type: string
          description: Cidade ou Estado da Franquia
          example: Brooklyn

        displayName:
          type: string
          description: Nome da Franquia
          example: Brooklin Nets

        shortName: 
          type: string
          example: Nets

        isActive:
          type: boolean
        
        logo_url: 
          type: string
          description: Link do Logo da Equipe
          example: https://a.espncdn.com/i/teamlogos/nba/500/bkn.png


        venue:
          type: string
          description: Arena 
          example: 'Barclays Center'


        

        


        

        

        